### PR TITLE
Add initial implementation of NullPointGenerator

### PR DESCRIPTION
**Pull request by xen-0**
The main function of this is to simply "multiply" existing generators
by adding an extra dimension. This adds no "axes" or new positions.

It can also be used on its own in a CompoundGenerator to provide empty
points.

### CODE REVIEW

**Comment by xen-0** [comment]
Feel free to suggest a better name.

**Comment by thomascobb** [comment]
How about RepeatGenerator?

-- 
This e-mail and any attachments may contain confidential, copyright and or privileged material, and are for the use of the intended addressee only. If you are not the intended addressee or an authorised recipient of the addressee please notify us of receipt by returning the e-mail and do not use, copy, retain, distribute or disclose the information in or attached to the e-mail.
Any opinions expressed within this e-mail are those of the individual and not necessarily of Diamond Light Source Ltd. 
Diamond Light Source Ltd. cannot guarantee that this e-mail or any attachments are free from viruses and we cannot accept liability for any damage which you may sustain as a result of software viruses which may be transmitted in or with the message.
Diamond Light Source Limited (company no. 4375679). Registered in England and Wales with its registered office at Diamond House, Harwell Science and Innovation Campus, Didcot, Oxfordshire, OX11 0DE, United Kingdom

**Comment by xen-0** [comment]
Does it make sense as a name for when it's shoved into a CompoundGenerator on its own?

**Comment by thomascobb** [comment]
Maybe, maybe not. I slightly prefer it to NullPointGenerator...

**Comment by xen-0** [comment]
Renamed to StaticPointGenerator by popular demand.

**Pull request merged**
